/*Create a basic version of Scissors Paper Stone where the user inputs one of "scissors", "paper", or "stone", the program internally randomly chooses scissors, paper, or stone, and the program outputs whether the user won, the program won, or it's a draw.
Rules: scissors beats paper, paper beats stone, and stone beats scissors. If both parties choose the same object, it's a draw.
*/
//global variable to set initial game states
var noOfUserWins = 0;
var noOfComWins = 0;
var noOfDraws = 0;
var currentGameMode = "waiting for username";
var userName = "";
var myOutputValue = "Hi! What's your name?";

var generateSPS = function () {
  //generate random number
  var randomNumber = Math.floor(Math.random() * 4);
  //assign scissors, paper, stone to the random number
  if (randomNumber == 1) {
    myOutputValue = "scissors";
  } else if (randomNumber == 2) {
    myOutputValue = "paper";
  } else {
    myOutputValue = "stone";
  }
  return myOutputValue;
};

var main = function (input) {
  //default myOutputValue
  var myOutputValue = "";
  //generate scissors paper or stone
  var generateByCom = generateSPS();
  //starting mode: user to input user name
  if (currentGameMode == "waiting for username") {
    //set the name
    userName = input;
    //change the mode after having username
    currentGameMode = "SPS";
    myOutputValue = `Hello ${userName}! Let's play scissors, paper, stone!`;
  }
  //error message
  else if (
    currentGameMode == "SPS" &&
    input != "scissors" &&
    input != "paper" &&
    input != "stone"
  ) {
    myOutputValue = "Please input scissors, paper or stone.";
  }
  //winning entries scenarios defined
  else if (
    (input == "scissors" && generateByCom == "paper") ||
    (input == "paper" && generateByCom == "stone") ||
    (input == "stone" && generateByCom == "scissors")
  ) {
    noOfUserWins = noOfUserWins + 1;
    myOutputValue = `You have chosen ${input}. The computer has chosen ${generateByCom}. You won! <br> Current score - ${userName}: ${noOfUserWins}, Computer: ${noOfComWins}`;
    console.log(
      `User: ${input}, Computer: ${generateByCom}
      No. of wins: ${noOfUserWins}
      No of losses: ${noOfComWins}
      No. of draws: ${noOfDraws}`
    );
  }
  //draw entries when input = generated by com
  else if (input == generateByCom) {
    noOfDraws = noOfDraws + 1;
    myOutputValue = `You have chosen ${input}. The computer has chosen ${generateByCom}. It is a draw! <br> Current score - ${userName}: ${noOfUserWins}, Computer: ${noOfComWins}`;
    console.log(
      `User: ${input}, Computer: ${generateByCom}
      No. of wins: ${noOfUserWins}
      No of losses: ${noOfComWins}
      No. of draws: ${noOfDraws}`
    );
  }
  //losing entries scenarios defined
  else {
    noOfComWins = noOfComWins + 1;
    myOutputValue = `You have chosen ${input}. The computer has chosen ${generateByCom}. You lost! <br> Current score - ${userName}: ${noOfUserWins}, Computer: ${noOfComWins}`;
    console.log(
      `User: ${input}, Computer: ${generateByCom}
      No. of wins: ${noOfUserWins}
      No of losses: ${noOfComWins}
      No. of draws: ${noOfDraws}`
    );
  }

  return myOutputValue;
};
